import { v4 as uuid } from 'uuid';
import type { AppModel, Feature } from '../types/models';

function features(list: Array<Pick<Feature, 'name' | 'priority' | 'progress' | 'status'>>): Feature[] {
  return list.map((f) => ({
    id: uuid(),
    context: '',
    ...f,
  }));
}

export function demoApps(): AppModel[] {
  const now = new Date();
  return [
    {
      id: uuid(),
      name: 'Cardify UI Kit',
      emoji: '🃏',
      suit: 'hearts',
      cardValue: 13,
      description: 'A reusable UI component kit styled like playing cards.',
      status: 'mvp',
      context: 'Design tokens, card animations, and themes.',
      features: features([
        { name: 'Card Flip Animation', priority: 'high', progress: 90, status: 'in-progress' },
        { name: 'Theme Switcher', priority: 'medium', progress: 60, status: 'in-progress' },
        { name: 'Component Docs', priority: 'low', progress: 20, status: 'planned' },
      ]),
      sharedComponents: [],
      perplexitySpace: { spaceId: '', spaceName: '', lastSyncAt: now, syncStatus: 'pending' },
      braindumpContent: { localContent: '', lastModified: now, wordCount: 0, ideaCount: 0 },
      createdAt: now,
      updatedAt: now,
      mvpPhases: [],
    },
    {
      id: uuid(),
      name: 'Sprint Deck',
      emoji: '🏁',
      suit: 'diamonds',
      cardValue: 10,
      description: 'Sprint planning visualized as a deck of cards.',
      status: 'development',
      context: 'Drag and drop, status lanes, and analytics.',
      features: features([
        { name: 'Drag & Drop', priority: 'high', progress: 75, status: 'in-progress' },
        { name: 'Burndown Chart', priority: 'medium', progress: 40, status: 'in-progress' },
        { name: 'Export CSV', priority: 'low', progress: 0, status: 'planned' },
      ]),
      sharedComponents: [],
      perplexitySpace: { spaceId: '', spaceName: '', lastSyncAt: now, syncStatus: 'pending' },
      braindumpContent: { localContent: '', lastModified: now, wordCount: 0, ideaCount: 0 },
      createdAt: now,
      updatedAt: now,
      mvpPhases: [],
    },
    {
      id: uuid(),
      name: 'Idea Forge',
      emoji: '🧠',
      suit: 'spades',
      cardValue: 7,
      description: 'Braindump with AI extraction for app ideas.',
      status: 'idea',
      context: 'Voice-to-text and Perplexity sync.',
      features: features([
        { name: 'Voice Notes', priority: 'medium', progress: 10, status: 'planned' },
        { name: 'AI Idea Extraction', priority: 'high', progress: 0, status: 'planned' },
      ]),
      sharedComponents: [],
      perplexitySpace: { spaceId: '', spaceName: '', lastSyncAt: now, syncStatus: 'pending' },
      braindumpContent: { localContent: '', lastModified: now, wordCount: 0, ideaCount: 0 },
      createdAt: now,
      updatedAt: now,
      mvpPhases: [],
    },
    {
      id: uuid(),
      name: 'Launch Tracker',
      emoji: '🚀',
      suit: 'clubs',
      cardValue: 12,
      description: 'Track app launches and post-launch KPIs.',
      status: 'complete',
      context: 'Live dashboard and milestones.',
      features: features([
        { name: 'Milestones', priority: 'high', progress: 100, status: 'complete' },
        { name: 'KPI Dashboard', priority: 'high', progress: 100, status: 'complete' },
      ]),
      sharedComponents: [],
      perplexitySpace: { spaceId: '', spaceName: '', lastSyncAt: now, syncStatus: 'synced' },
      braindumpContent: { localContent: '', lastModified: now, wordCount: 0, ideaCount: 0 },
      createdAt: now,
      updatedAt: now,
      mvpPhases: [],
    },
    {
      id: uuid(),
      name: 'Component Vault',
      emoji: '🧩',
      suit: 'diamonds',
      cardValue: 8,
      description: 'Global components library with versioning.',
      status: 'development',
      context: 'Usage tracking across apps.',
      features: features([
        { name: 'Versioning', priority: 'high', progress: 30, status: 'in-progress' },
        { name: 'Usage Graph', priority: 'medium', progress: 10, status: 'planned' },
      ]),
      sharedComponents: [],
      perplexitySpace: { spaceId: '', spaceName: '', lastSyncAt: now, syncStatus: 'pending' },
      braindumpContent: { localContent: '', lastModified: now, wordCount: 0, ideaCount: 0 },
      createdAt: now,
      updatedAt: now,
      mvpPhases: [],
    },
    {
      id: uuid(),
      name: 'Daily Streaks',
      emoji: '🔥',
      suit: 'hearts',
      cardValue: 11,
      description: 'Gamified streak tracking for dev sessions.',
      status: 'mvp',
      context: 'Celebrations and achievements.',
      features: features([
        { name: 'Streak Counter', priority: 'high', progress: 70, status: 'in-progress' },
        { name: 'Achievements', priority: 'medium', progress: 20, status: 'planned' },
      ]),
      sharedComponents: [],
      perplexitySpace: { spaceId: '', spaceName: '', lastSyncAt: now, syncStatus: 'pending' },
      braindumpContent: { localContent: '', lastModified: now, wordCount: 0, ideaCount: 0 },
      createdAt: now,
      updatedAt: now,
      mvpPhases: [],
    },
  ];
}

